name: CI-Golang

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  # Run linting
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.21]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Lint Files
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            echo "Go code is not properly formatted"
            gofmt -d .
            exit 1
          fi
